const appRoutes = {
    ROUTE_HOME: '/',
    ROUTE_ADMINS: '/admins',
    ROUTE_USERS: '/users',
    ROUTE_SPECIALTIES: '/specialties',
    ROUTE_HOSPITALS: '/hospitals',
    ROUTE_SYMPTOMS: '/symptoms',
    ROUTE_GROUPS: '/groups',
    ROUTE_CATEGORIES: '/categories',
    ROUTE_EXAMS: '/exams',
    ROUTE_PATIENTS: '/patients',
    ROUTE_NURSES: '/nurses',
    ROUTE_ANALYSTS: '/analysts',
    ROUTE_DOCTORS: '/doctors',
    ROUTE_ADD_DOCTOR: '/doctors/add',
    ROUTE_ADD_NURSE: '/nurses/add',
    ROUTE_ADD_PATIENT: '/patients/add',
    ROUTE_ADD_ADMIN: '/admins/add',
    ROUTE_ADD_ANALYST: '/analysts/add',
    ROUTE_ADD_SPECIALITY: '/specialties/add',
    ROUTE_ADD_SYMPTOM: '/symptoms/add',
    ROUTE_ADD_HOSPITAL: '/hospitals/add',
    ROUTE_ADD_EXAM: '/exams/add',
    ROUTE_ADD_CATEGORY: '/categories/add',
    ROUTE_ADD_GROUP: '/groups/add',
    ROUTE_LOGIN: '/login',
    ROUTE_ERROR: '/_error',
}
const apiRoutes = {
    ADD_DOCTOR: '/doctors',
    ADD_NURSE: '/nurses',
    ADD_PATIENT: '/patients',
    ADD_ANALYST: '/analysts',
    ADD_SPECIALITY: '/specialties',
    ADD_ADMIN: '/users',
    ADD_SYMPTOM: '/consultations/symptoms',
    ADD_EXAM: '/consultations/exams',
    ADD_CATEGORY: '/consultations/categories',
    ADD_GROUP: '/consultations/groups',
    EDIT_GROUP: '/consultations/groups',
    GET_PATIENTS: '/patients',
    GET_ADMINS: '/users/admins',
    GET_USERS: '/users',
    USERS: '/users',
    GET_ANALYSTS: '/analysts',
    GET_DOCTORS: '/doctors',
    GET_NURSES: '/nurses',
    SPECIALTIES: '/specialties',
    HOSPITALS: '/hospitals',
    DOCTORS: '/doctors',
    NURSES: '/nurses',
    PATIENTS: '/patients',
    SYMPTOMS: '/consultations/symptoms',
    CATEGORIES: '/consultations/categories',
    EXAMS: '/consultations/exams',
    GROUPS: '/consultations/groups',
    GET_AUTHORITIES: '/users/authorities',
    BASE_URL: 'https://backoffice-g4q4drrkla-uc.a.run.app/api',
    GET_CURRENT_USER: '/users/account',
    LOGIN: '/users/login',
    GET_AVATAR: (avatarId) => `${process.env.NEXT_PUBLIC_API_URL}/users/avatar/${avatarId}`,
}
export {appRoutes, apiRoutes}

export const ITEMS_PER_PAGE = 10